/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoConsultationRouteImport } from './routes/video-consultation'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PaymentSummaryRouteImport } from './routes/payment-summary'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffPaymentsRouteImport } from './routes/staff/payments'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as StaffDashboardRouteImport } from './routes/staff/dashboard'
import { Route as StaffAppointmentsRouteImport } from './routes/staff/appointments'
import { Route as StaffAdminRouteImport } from './routes/staff/admin'
import { Route as AppointmentsAppointmentIdRouteImport } from './routes/appointments/$appointmentId'
import { Route as ApiSendPushRouteImport } from './routes/api/send-push'
import { Route as ApiAgoraTokenRouteImport } from './routes/api/agora-token'
import { Route as StaffPatientsIndexRouteImport } from './routes/staff/patients/index'
import { Route as StaffStaffAccountsCreateRouteImport } from './routes/staff/staff-accounts/create'
import { Route as StaffPharmacyPrescriptionsRouteImport } from './routes/staff/pharmacy/prescriptions'
import { Route as StaffPharmacyInventoryRouteImport } from './routes/staff/pharmacy/inventory'
import { Route as StaffPharmacyDispensedRouteImport } from './routes/staff/pharmacy/dispensed'
import { Route as StaffPharmacyDashboardRouteImport } from './routes/staff/pharmacy/dashboard'
import { Route as StaffPatientsNewRouteImport } from './routes/staff/patients/new'
import { Route as StaffPatientsMrnRouteImport } from './routes/staff/patients/$mrn'
import { Route as StaffLaboratoryResultsRouteImport } from './routes/staff/laboratory/results'
import { Route as StaffLaboratoryRequestsRouteImport } from './routes/staff/laboratory/requests'
import { Route as StaffLaboratoryDashboardRouteImport } from './routes/staff/laboratory/dashboard'
import { Route as StaffDoctorQueueRouteImport } from './routes/staff/doctor/queue'
import { Route as StaffDoctorLabResultsRouteImport } from './routes/staff/doctor/lab-results'
import { Route as StaffDoctorDashboardRouteImport } from './routes/staff/doctor/dashboard'
import { Route as ConsultationRoomIdRouteImport } from './routes/consultation.room.$id'
import { Route as StaffLaboratoryPatientMrnRouteImport } from './routes/staff/laboratory/patient/$mrn'
import { Route as StaffDoctorPatientMrnRouteImport } from './routes/staff/doctor/patient/$mrn'

const VideoConsultationRoute = VideoConsultationRouteImport.update({
  id: '/video-consultation',
  path: '/video-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSummaryRoute = PaymentSummaryRouteImport.update({
  id: '/payment-summary',
  path: '/payment-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPaymentsRoute = StaffPaymentsRouteImport.update({
  id: '/staff/payments',
  path: '/staff/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAppointmentsRoute = StaffAppointmentsRouteImport.update({
  id: '/staff/appointments',
  path: '/staff/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAdminRoute = StaffAdminRouteImport.update({
  id: '/staff/admin',
  path: '/staff/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsAppointmentIdRoute =
  AppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSendPushRoute = ApiSendPushRouteImport.update({
  id: '/api/send-push',
  path: '/api/send-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgoraTokenRoute = ApiAgoraTokenRouteImport.update({
  id: '/api/agora-token',
  path: '/api/agora-token',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPatientsIndexRoute = StaffPatientsIndexRouteImport.update({
  id: '/staff/patients/',
  path: '/staff/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffAccountsCreateRoute =
  StaffStaffAccountsCreateRouteImport.update({
    id: '/staff/staff-accounts/create',
    path: '/staff/staff-accounts/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffPharmacyPrescriptionsRoute =
  StaffPharmacyPrescriptionsRouteImport.update({
    id: '/staff/pharmacy/prescriptions',
    path: '/staff/pharmacy/prescriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffPharmacyInventoryRoute = StaffPharmacyInventoryRouteImport.update({
  id: '/staff/pharmacy/inventory',
  path: '/staff/pharmacy/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPharmacyDispensedRoute = StaffPharmacyDispensedRouteImport.update({
  id: '/staff/pharmacy/dispensed',
  path: '/staff/pharmacy/dispensed',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPharmacyDashboardRoute = StaffPharmacyDashboardRouteImport.update({
  id: '/staff/pharmacy/dashboard',
  path: '/staff/pharmacy/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPatientsNewRoute = StaffPatientsNewRouteImport.update({
  id: '/staff/patients/new',
  path: '/staff/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPatientsMrnRoute = StaffPatientsMrnRouteImport.update({
  id: '/staff/patients/$mrn',
  path: '/staff/patients/$mrn',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLaboratoryResultsRoute = StaffLaboratoryResultsRouteImport.update({
  id: '/staff/laboratory/results',
  path: '/staff/laboratory/results',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLaboratoryRequestsRoute = StaffLaboratoryRequestsRouteImport.update({
  id: '/staff/laboratory/requests',
  path: '/staff/laboratory/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLaboratoryDashboardRoute =
  StaffLaboratoryDashboardRouteImport.update({
    id: '/staff/laboratory/dashboard',
    path: '/staff/laboratory/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffDoctorQueueRoute = StaffDoctorQueueRouteImport.update({
  id: '/staff/doctor/queue',
  path: '/staff/doctor/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDoctorLabResultsRoute = StaffDoctorLabResultsRouteImport.update({
  id: '/staff/doctor/lab-results',
  path: '/staff/doctor/lab-results',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDoctorDashboardRoute = StaffDoctorDashboardRouteImport.update({
  id: '/staff/doctor/dashboard',
  path: '/staff/doctor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoomIdRoute = ConsultationRoomIdRouteImport.update({
  id: '/consultation/room/$id',
  path: '/consultation/room/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLaboratoryPatientMrnRoute =
  StaffLaboratoryPatientMrnRouteImport.update({
    id: '/staff/laboratory/patient/$mrn',
    path: '/staff/laboratory/patient/$mrn',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffDoctorPatientMrnRoute = StaffDoctorPatientMrnRouteImport.update({
  id: '/staff/doctor/patient/$mrn',
  path: '/staff/doctor/patient/$mrn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/payment-summary': typeof PaymentSummaryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video-consultation': typeof VideoConsultationRoute
  '/api/agora-token': typeof ApiAgoraTokenRoute
  '/api/send-push': typeof ApiSendPushRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/staff/admin': typeof StaffAdminRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/payments': typeof StaffPaymentsRoute
  '/consultation/room/$id': typeof ConsultationRoomIdRoute
  '/staff/doctor/dashboard': typeof StaffDoctorDashboardRoute
  '/staff/doctor/lab-results': typeof StaffDoctorLabResultsRoute
  '/staff/doctor/queue': typeof StaffDoctorQueueRoute
  '/staff/laboratory/dashboard': typeof StaffLaboratoryDashboardRoute
  '/staff/laboratory/requests': typeof StaffLaboratoryRequestsRoute
  '/staff/laboratory/results': typeof StaffLaboratoryResultsRoute
  '/staff/patients/$mrn': typeof StaffPatientsMrnRoute
  '/staff/patients/new': typeof StaffPatientsNewRoute
  '/staff/pharmacy/dashboard': typeof StaffPharmacyDashboardRoute
  '/staff/pharmacy/dispensed': typeof StaffPharmacyDispensedRoute
  '/staff/pharmacy/inventory': typeof StaffPharmacyInventoryRoute
  '/staff/pharmacy/prescriptions': typeof StaffPharmacyPrescriptionsRoute
  '/staff/staff-accounts/create': typeof StaffStaffAccountsCreateRoute
  '/staff/patients/': typeof StaffPatientsIndexRoute
  '/staff/doctor/patient/$mrn': typeof StaffDoctorPatientMrnRoute
  '/staff/laboratory/patient/$mrn': typeof StaffLaboratoryPatientMrnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/payment-summary': typeof PaymentSummaryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video-consultation': typeof VideoConsultationRoute
  '/api/agora-token': typeof ApiAgoraTokenRoute
  '/api/send-push': typeof ApiSendPushRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/staff/admin': typeof StaffAdminRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/payments': typeof StaffPaymentsRoute
  '/consultation/room/$id': typeof ConsultationRoomIdRoute
  '/staff/doctor/dashboard': typeof StaffDoctorDashboardRoute
  '/staff/doctor/lab-results': typeof StaffDoctorLabResultsRoute
  '/staff/doctor/queue': typeof StaffDoctorQueueRoute
  '/staff/laboratory/dashboard': typeof StaffLaboratoryDashboardRoute
  '/staff/laboratory/requests': typeof StaffLaboratoryRequestsRoute
  '/staff/laboratory/results': typeof StaffLaboratoryResultsRoute
  '/staff/patients/$mrn': typeof StaffPatientsMrnRoute
  '/staff/patients/new': typeof StaffPatientsNewRoute
  '/staff/pharmacy/dashboard': typeof StaffPharmacyDashboardRoute
  '/staff/pharmacy/dispensed': typeof StaffPharmacyDispensedRoute
  '/staff/pharmacy/inventory': typeof StaffPharmacyInventoryRoute
  '/staff/pharmacy/prescriptions': typeof StaffPharmacyPrescriptionsRoute
  '/staff/staff-accounts/create': typeof StaffStaffAccountsCreateRoute
  '/staff/patients': typeof StaffPatientsIndexRoute
  '/staff/doctor/patient/$mrn': typeof StaffDoctorPatientMrnRoute
  '/staff/laboratory/patient/$mrn': typeof StaffLaboratoryPatientMrnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/payment-summary': typeof PaymentSummaryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video-consultation': typeof VideoConsultationRoute
  '/api/agora-token': typeof ApiAgoraTokenRoute
  '/api/send-push': typeof ApiSendPushRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/staff/admin': typeof StaffAdminRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/payments': typeof StaffPaymentsRoute
  '/consultation/room/$id': typeof ConsultationRoomIdRoute
  '/staff/doctor/dashboard': typeof StaffDoctorDashboardRoute
  '/staff/doctor/lab-results': typeof StaffDoctorLabResultsRoute
  '/staff/doctor/queue': typeof StaffDoctorQueueRoute
  '/staff/laboratory/dashboard': typeof StaffLaboratoryDashboardRoute
  '/staff/laboratory/requests': typeof StaffLaboratoryRequestsRoute
  '/staff/laboratory/results': typeof StaffLaboratoryResultsRoute
  '/staff/patients/$mrn': typeof StaffPatientsMrnRoute
  '/staff/patients/new': typeof StaffPatientsNewRoute
  '/staff/pharmacy/dashboard': typeof StaffPharmacyDashboardRoute
  '/staff/pharmacy/dispensed': typeof StaffPharmacyDispensedRoute
  '/staff/pharmacy/inventory': typeof StaffPharmacyInventoryRoute
  '/staff/pharmacy/prescriptions': typeof StaffPharmacyPrescriptionsRoute
  '/staff/staff-accounts/create': typeof StaffStaffAccountsCreateRoute
  '/staff/patients/': typeof StaffPatientsIndexRoute
  '/staff/doctor/patient/$mrn': typeof StaffDoctorPatientMrnRoute
  '/staff/laboratory/patient/$mrn': typeof StaffLaboratoryPatientMrnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/departments'
    | '/doctors'
    | '/gallery'
    | '/payment-success'
    | '/payment-summary'
    | '/services'
    | '/sitemap.xml'
    | '/video-consultation'
    | '/api/agora-token'
    | '/api/send-push'
    | '/appointments/$appointmentId'
    | '/staff/admin'
    | '/staff/appointments'
    | '/staff/dashboard'
    | '/staff/login'
    | '/staff/payments'
    | '/consultation/room/$id'
    | '/staff/doctor/dashboard'
    | '/staff/doctor/lab-results'
    | '/staff/doctor/queue'
    | '/staff/laboratory/dashboard'
    | '/staff/laboratory/requests'
    | '/staff/laboratory/results'
    | '/staff/patients/$mrn'
    | '/staff/patients/new'
    | '/staff/pharmacy/dashboard'
    | '/staff/pharmacy/dispensed'
    | '/staff/pharmacy/inventory'
    | '/staff/pharmacy/prescriptions'
    | '/staff/staff-accounts/create'
    | '/staff/patients/'
    | '/staff/doctor/patient/$mrn'
    | '/staff/laboratory/patient/$mrn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/departments'
    | '/doctors'
    | '/gallery'
    | '/payment-success'
    | '/payment-summary'
    | '/services'
    | '/sitemap.xml'
    | '/video-consultation'
    | '/api/agora-token'
    | '/api/send-push'
    | '/appointments/$appointmentId'
    | '/staff/admin'
    | '/staff/appointments'
    | '/staff/dashboard'
    | '/staff/login'
    | '/staff/payments'
    | '/consultation/room/$id'
    | '/staff/doctor/dashboard'
    | '/staff/doctor/lab-results'
    | '/staff/doctor/queue'
    | '/staff/laboratory/dashboard'
    | '/staff/laboratory/requests'
    | '/staff/laboratory/results'
    | '/staff/patients/$mrn'
    | '/staff/patients/new'
    | '/staff/pharmacy/dashboard'
    | '/staff/pharmacy/dispensed'
    | '/staff/pharmacy/inventory'
    | '/staff/pharmacy/prescriptions'
    | '/staff/staff-accounts/create'
    | '/staff/patients'
    | '/staff/doctor/patient/$mrn'
    | '/staff/laboratory/patient/$mrn'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/departments'
    | '/doctors'
    | '/gallery'
    | '/payment-success'
    | '/payment-summary'
    | '/services'
    | '/sitemap.xml'
    | '/video-consultation'
    | '/api/agora-token'
    | '/api/send-push'
    | '/appointments/$appointmentId'
    | '/staff/admin'
    | '/staff/appointments'
    | '/staff/dashboard'
    | '/staff/login'
    | '/staff/payments'
    | '/consultation/room/$id'
    | '/staff/doctor/dashboard'
    | '/staff/doctor/lab-results'
    | '/staff/doctor/queue'
    | '/staff/laboratory/dashboard'
    | '/staff/laboratory/requests'
    | '/staff/laboratory/results'
    | '/staff/patients/$mrn'
    | '/staff/patients/new'
    | '/staff/pharmacy/dashboard'
    | '/staff/pharmacy/dispensed'
    | '/staff/pharmacy/inventory'
    | '/staff/pharmacy/prescriptions'
    | '/staff/staff-accounts/create'
    | '/staff/patients/'
    | '/staff/doctor/patient/$mrn'
    | '/staff/laboratory/patient/$mrn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DoctorsRoute: typeof DoctorsRoute
  GalleryRoute: typeof GalleryRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PaymentSummaryRoute: typeof PaymentSummaryRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VideoConsultationRoute: typeof VideoConsultationRoute
  ApiAgoraTokenRoute: typeof ApiAgoraTokenRoute
  ApiSendPushRoute: typeof ApiSendPushRoute
  AppointmentsAppointmentIdRoute: typeof AppointmentsAppointmentIdRoute
  StaffAdminRoute: typeof StaffAdminRoute
  StaffAppointmentsRoute: typeof StaffAppointmentsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffPaymentsRoute: typeof StaffPaymentsRoute
  ConsultationRoomIdRoute: typeof ConsultationRoomIdRoute
  StaffDoctorDashboardRoute: typeof StaffDoctorDashboardRoute
  StaffDoctorLabResultsRoute: typeof StaffDoctorLabResultsRoute
  StaffDoctorQueueRoute: typeof StaffDoctorQueueRoute
  StaffLaboratoryDashboardRoute: typeof StaffLaboratoryDashboardRoute
  StaffLaboratoryRequestsRoute: typeof StaffLaboratoryRequestsRoute
  StaffLaboratoryResultsRoute: typeof StaffLaboratoryResultsRoute
  StaffPatientsMrnRoute: typeof StaffPatientsMrnRoute
  StaffPatientsNewRoute: typeof StaffPatientsNewRoute
  StaffPharmacyDashboardRoute: typeof StaffPharmacyDashboardRoute
  StaffPharmacyDispensedRoute: typeof StaffPharmacyDispensedRoute
  StaffPharmacyInventoryRoute: typeof StaffPharmacyInventoryRoute
  StaffPharmacyPrescriptionsRoute: typeof StaffPharmacyPrescriptionsRoute
  StaffStaffAccountsCreateRoute: typeof StaffStaffAccountsCreateRoute
  StaffPatientsIndexRoute: typeof StaffPatientsIndexRoute
  StaffDoctorPatientMrnRoute: typeof StaffDoctorPatientMrnRoute
  StaffLaboratoryPatientMrnRoute: typeof StaffLaboratoryPatientMrnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-consultation': {
      id: '/video-consultation'
      path: '/video-consultation'
      fullPath: '/video-consultation'
      preLoaderRoute: typeof VideoConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-summary': {
      id: '/payment-summary'
      path: '/payment-summary'
      fullPath: '/payment-summary'
      preLoaderRoute: typeof PaymentSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/payments': {
      id: '/staff/payments'
      path: '/staff/payments'
      fullPath: '/staff/payments'
      preLoaderRoute: typeof StaffPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/appointments': {
      id: '/staff/appointments'
      path: '/staff/appointments'
      fullPath: '/staff/appointments'
      preLoaderRoute: typeof StaffAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/admin': {
      id: '/staff/admin'
      path: '/staff/admin'
      fullPath: '/staff/admin'
      preLoaderRoute: typeof StaffAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$appointmentId': {
      id: '/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof AppointmentsAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-push': {
      id: '/api/send-push'
      path: '/api/send-push'
      fullPath: '/api/send-push'
      preLoaderRoute: typeof ApiSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agora-token': {
      id: '/api/agora-token'
      path: '/api/agora-token'
      fullPath: '/api/agora-token'
      preLoaderRoute: typeof ApiAgoraTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/patients/': {
      id: '/staff/patients/'
      path: '/staff/patients'
      fullPath: '/staff/patients/'
      preLoaderRoute: typeof StaffPatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/staff-accounts/create': {
      id: '/staff/staff-accounts/create'
      path: '/staff/staff-accounts/create'
      fullPath: '/staff/staff-accounts/create'
      preLoaderRoute: typeof StaffStaffAccountsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/pharmacy/prescriptions': {
      id: '/staff/pharmacy/prescriptions'
      path: '/staff/pharmacy/prescriptions'
      fullPath: '/staff/pharmacy/prescriptions'
      preLoaderRoute: typeof StaffPharmacyPrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/pharmacy/inventory': {
      id: '/staff/pharmacy/inventory'
      path: '/staff/pharmacy/inventory'
      fullPath: '/staff/pharmacy/inventory'
      preLoaderRoute: typeof StaffPharmacyInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/pharmacy/dispensed': {
      id: '/staff/pharmacy/dispensed'
      path: '/staff/pharmacy/dispensed'
      fullPath: '/staff/pharmacy/dispensed'
      preLoaderRoute: typeof StaffPharmacyDispensedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/pharmacy/dashboard': {
      id: '/staff/pharmacy/dashboard'
      path: '/staff/pharmacy/dashboard'
      fullPath: '/staff/pharmacy/dashboard'
      preLoaderRoute: typeof StaffPharmacyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/patients/new': {
      id: '/staff/patients/new'
      path: '/staff/patients/new'
      fullPath: '/staff/patients/new'
      preLoaderRoute: typeof StaffPatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/patients/$mrn': {
      id: '/staff/patients/$mrn'
      path: '/staff/patients/$mrn'
      fullPath: '/staff/patients/$mrn'
      preLoaderRoute: typeof StaffPatientsMrnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/laboratory/results': {
      id: '/staff/laboratory/results'
      path: '/staff/laboratory/results'
      fullPath: '/staff/laboratory/results'
      preLoaderRoute: typeof StaffLaboratoryResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/laboratory/requests': {
      id: '/staff/laboratory/requests'
      path: '/staff/laboratory/requests'
      fullPath: '/staff/laboratory/requests'
      preLoaderRoute: typeof StaffLaboratoryRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/laboratory/dashboard': {
      id: '/staff/laboratory/dashboard'
      path: '/staff/laboratory/dashboard'
      fullPath: '/staff/laboratory/dashboard'
      preLoaderRoute: typeof StaffLaboratoryDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/doctor/queue': {
      id: '/staff/doctor/queue'
      path: '/staff/doctor/queue'
      fullPath: '/staff/doctor/queue'
      preLoaderRoute: typeof StaffDoctorQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/doctor/lab-results': {
      id: '/staff/doctor/lab-results'
      path: '/staff/doctor/lab-results'
      fullPath: '/staff/doctor/lab-results'
      preLoaderRoute: typeof StaffDoctorLabResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/doctor/dashboard': {
      id: '/staff/doctor/dashboard'
      path: '/staff/doctor/dashboard'
      fullPath: '/staff/doctor/dashboard'
      preLoaderRoute: typeof StaffDoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation/room/$id': {
      id: '/consultation/room/$id'
      path: '/consultation/room/$id'
      fullPath: '/consultation/room/$id'
      preLoaderRoute: typeof ConsultationRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/laboratory/patient/$mrn': {
      id: '/staff/laboratory/patient/$mrn'
      path: '/staff/laboratory/patient/$mrn'
      fullPath: '/staff/laboratory/patient/$mrn'
      preLoaderRoute: typeof StaffLaboratoryPatientMrnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/doctor/patient/$mrn': {
      id: '/staff/doctor/patient/$mrn'
      path: '/staff/doctor/patient/$mrn'
      fullPath: '/staff/doctor/patient/$mrn'
      preLoaderRoute: typeof StaffDoctorPatientMrnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  DoctorsRoute: DoctorsRoute,
  GalleryRoute: GalleryRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PaymentSummaryRoute: PaymentSummaryRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VideoConsultationRoute: VideoConsultationRoute,
  ApiAgoraTokenRoute: ApiAgoraTokenRoute,
  ApiSendPushRoute: ApiSendPushRoute,
  AppointmentsAppointmentIdRoute: AppointmentsAppointmentIdRoute,
  StaffAdminRoute: StaffAdminRoute,
  StaffAppointmentsRoute: StaffAppointmentsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffPaymentsRoute: StaffPaymentsRoute,
  ConsultationRoomIdRoute: ConsultationRoomIdRoute,
  StaffDoctorDashboardRoute: StaffDoctorDashboardRoute,
  StaffDoctorLabResultsRoute: StaffDoctorLabResultsRoute,
  StaffDoctorQueueRoute: StaffDoctorQueueRoute,
  StaffLaboratoryDashboardRoute: StaffLaboratoryDashboardRoute,
  StaffLaboratoryRequestsRoute: StaffLaboratoryRequestsRoute,
  StaffLaboratoryResultsRoute: StaffLaboratoryResultsRoute,
  StaffPatientsMrnRoute: StaffPatientsMrnRoute,
  StaffPatientsNewRoute: StaffPatientsNewRoute,
  StaffPharmacyDashboardRoute: StaffPharmacyDashboardRoute,
  StaffPharmacyDispensedRoute: StaffPharmacyDispensedRoute,
  StaffPharmacyInventoryRoute: StaffPharmacyInventoryRoute,
  StaffPharmacyPrescriptionsRoute: StaffPharmacyPrescriptionsRoute,
  StaffStaffAccountsCreateRoute: StaffStaffAccountsCreateRoute,
  StaffPatientsIndexRoute: StaffPatientsIndexRoute,
  StaffDoctorPatientMrnRoute: StaffDoctorPatientMrnRoute,
  StaffLaboratoryPatientMrnRoute: StaffLaboratoryPatientMrnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
